Repository Tea-Bliss/FE_Tea_Bliss, pull requests merged in 2024-06, with the labels that each got.

#20 Feature/#8 회원가입페이지
  package-lock.json
  package.json
  public/icons/checkedBox.svg
  public/icons/unCheckedBox.svg
  public/images/logo.svg
  src/app/sign-up/page.tsx
  src/components/common/Button/index.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Input/Input.tsx
  src/components/common/Label/Label.tsx
  src/components/common/RadioInput/RadioInput.module.scss
  src/components/common/RadioInput/RadioInput.tsx
  src/components/page-layout/signUpLayout/signUpForm/signUpForm.module.scss
  src/components/page-layout/signUpLayout/signUpForm/signUpForm.tsx
  src/components/page-layout/signUpLayout/signUpLayout.module.scss
  src/components/page-layout/signUpLayout/signUpLayout.tsx
Labels: feat

#19 feat: 티 블렌딩 페이지 라벨 컴포넌트
  src/components/common/BlendingLabel/BlendingLabel.module.scss
  src/components/common/BlendingLabel/BlendingLabel.tsx
  src/components/common/BlendingLabel/constants/labelType.ts
Labels: feat

#23 feat: 로그인 페이지 구현
  public/icons/goggle.svg
  public/icons/kakao.svg
  src/app/sign-in/page.tsx
  src/components/page-layout/signInLayout/signInForm/signInForm.module.scss
  src/components/page-layout/signInLayout/signInForm/signInForm.tsx
  src/components/page-layout/signInLayout/signInLayout.module.scss
  src/components/page-layout/signInLayout/signInLayout.tsx
  src/components/page-layout/signInLayout/socialLogin/socialLogin.module.scss
  src/components/page-layout/signInLayout/socialLogin/socialLogin.tsx
  src/components/page-layout/signUpLayout/signUpLayout.tsx
  src/styles/_color.scss
Labels: feat

#25 [페이지] my-blending 페이지 전체 UI 구조
  public/images/my-blending/vanila.png
  src/app/my-blending/page.tsx
  src/components/common/BlendingLabel/BlendingLabel.module.scss
  src/components/common/BlendingLabel/constants/labelType.ts
  src/components/common/Button/Button.module.scss
  src/components/page-layout/myBlendingLayout/MyBlendingLayout.module.scss
  src/components/page-layout/myBlendingLayout/components/FixedBottomBar/FixedBottomBar.module.scss
  src/components/page-layout/myBlendingLayout/components/FixedBottomBar/index.tsx
  src/components/page-layout/myBlendingLayout/components/SortingMenu/SortingMenu.module.scss
  src/components/page-layout/myBlendingLayout/components/SortingMenu/TasteSortingList/TasteSortingList.module.scss
  src/components/page-layout/myBlendingLayout/components/SortingMenu/TasteSortingList/index.tsx
  src/components/page-layout/myBlendingLayout/components/SortingMenu/TypeSortingList/TypeSortingList.module.scss
  src/components/page-layout/myBlendingLayout/components/SortingMenu/TypeSortingList/indext.tsx
  src/components/page-layout/myBlendingLayout/components/SortingMenu/index.tsx
  src/components/page-layout/myBlendingLayout/components/TeaCardList/TeaCard/AddRemoveIcon/AddRemoveIcon.module.scss
  src/components/page-layout/myBlendingLayout/components/TeaCardList/TeaCard/AddRemoveIcon/index.tsx
  src/components/page-layout/myBlendingLayout/components/TeaCardList/TeaCard/CheckIcon/CheckIcon.module.scss
  src/components/page-layout/myBlendingLayout/components/TeaCardList/TeaCard/CheckIcon/index.tsx
  src/components/page-layout/myBlendingLayout/components/TeaCardList/TeaCard/TeaCard.module.scss
  src/components/page-layout/myBlendingLayout/components/TeaCardList/TeaCard/index.tsx
  src/components/page-layout/myBlendingLayout/components/TeaCardList/TeaCardList.module.scss
  src/components/page-layout/myBlendingLayout/components/TeaCardList/index.tsx
  src/components/page-layout/myBlendingLayout/constants/standards.ts
  src/components/page-layout/myBlendingLayout/contexts/myBlendingContext.tsx
  src/components/page-layout/myBlendingLayout/index.tsx
  src/components/page-layout/myBlendingLayout/types/teaType.ts
Labels: feat

#33 [페이지] 제품 목록 페이지 구현
  public/icons/arrow.svg
  public/icons/doubleArrow.svg
  public/images/product_banner.jpg
  src/app/product/list/page.tsx
  src/components/common/Card/Card.module.scss
  src/components/common/Card/Card.tsx
  src/components/common/Pagenation/Pagenation.module.scss
  src/components/common/Pagenation/Pagenation.tsx
  src/components/common/Pagenation/apis/getPagenationItems.ts
  src/components/page-layout/myBlendingLayout/index.tsx
  src/components/page-layout/productListLayout/ProductList/ProductList.module.scss
  src/components/page-layout/productListLayout/ProductList/ProductList.tsx
  src/components/page-layout/productListLayout/ProductNav/ProductNav.module.scss
  src/components/page-layout/productListLayout/ProductNav/ProductNav.tsx
  src/components/page-layout/productListLayout/constants/filter.ts
  src/components/page-layout/productListLayout/constants/mock.ts
  src/components/page-layout/productListLayout/constants/nav.ts
  src/components/page-layout/productListLayout/productListLayout.module.scss
  src/components/page-layout/productListLayout/productListLayout.tsx
Labels: feat

#32 [페이지] survey 페이지 UI 구현
  src/app/survey/page.tsx
  src/components/page-layout/myBlendingLayout/components/FixedBottomBar/index.tsx
  src/components/page-layout/myBlendingLayout/components/SortingMenu/TasteSortingList/index.tsx
  src/components/page-layout/myBlendingLayout/components/SortingMenu/TypeSortingList/index.tsx
  src/components/page-layout/myBlendingLayout/components/SortingMenu/index.tsx
  src/components/page-layout/myBlendingLayout/components/TeaCardList/TeaCard/AddRemoveIcon/index.tsx
  src/components/page-layout/myBlendingLayout/components/TeaCardList/TeaCard/CheckIcon/index.tsx
  src/components/page-layout/myBlendingLayout/components/TeaCardList/TeaCard/index.tsx
  src/components/page-layout/myBlendingLayout/components/TeaCardList/index.tsx
  src/components/page-layout/surveyLayout/SurveyLayout.module.scss
  src/components/page-layout/surveyLayout/components/ButtonInputs/ButtonInput/ButtonInput.module.scss
  src/components/page-layout/surveyLayout/components/ButtonInputs/ButtonInput/index.tsx
  src/components/page-layout/surveyLayout/components/ButtonInputs/ButtonInputs.module.scss
  src/components/page-layout/surveyLayout/components/ButtonInputs/index.tsx
  src/components/page-layout/surveyLayout/components/CheckBoxInputs/CheckBoxInput/CheckBoxInput.module.scss
  src/components/page-layout/surveyLayout/components/CheckBoxInputs/CheckBoxInput/index.tsx
  src/components/page-layout/surveyLayout/components/CheckBoxInputs/CheckBoxInputs.module.scss
  src/components/page-layout/surveyLayout/components/CheckBoxInputs/index.tsx
  src/components/page-layout/surveyLayout/components/FormDesign/FormDesign.module.scss
  src/components/page-layout/surveyLayout/components/FormDesign/index.tsx
  src/components/page-layout/surveyLayout/components/FormIcon/FormIcon.module.scss
  src/components/page-layout/surveyLayout/components/FormIcon/index.tsx
  src/components/page-layout/surveyLayout/components/SurveyForm/SurveyForm.module.scss
  src/components/page-layout/surveyLayout/components/SurveyForm/index.tsx
  src/components/page-layout/surveyLayout/constants/teaTypes.ts
  src/components/page-layout/surveyLayout/index.tsx
Labels: feat

#36 [공통] 드롭다운 컴포넌트 구현
  public/icons/chevron.svg
  src/components/common/DropDown/DropDown.tsx
  src/components/common/DropDown/DropDownContent.module.scss
  src/components/common/DropDown/DropDownContent.tsx
  src/components/common/DropDown/DropDownItem.tsx
  src/components/common/DropDown/DropDownTrigger.tsx
  src/components/common/DropDown/contexts/DropDownContext.ts
Labels: feat

#39 [페이지] 제품 목록 페이지 수정
  public/icons/doubleArrow.svg
  src/apis/axiosInstance.ts
  src/app/product/list/[id]/page.tsx
  src/components/common/Pagenation/Pagenation.module.scss
  src/components/common/Pagenation/Pagenation.tsx
  src/components/common/Pagenation/apis/getPagenationItems.ts
  src/components/common/Pagenation/types/index.ts
  src/components/page-layout/productListLayout/ProductList/ProductList.tsx
  src/components/page-layout/productListLayout/ProductNav/ProductNav.tsx
  src/components/page-layout/productListLayout/constants/filter.ts
  src/components/page-layout/productListLayout/constants/index.ts
  src/components/page-layout/productListLayout/constants/mock.ts
  src/components/page-layout/productListLayout/constants/nav.ts
  src/components/page-layout/productListLayout/types/index.ts
  src/constants/route.ts
Labels: refactor

#40 [페이지] admin 페이지 초안
  package-lock.json
  package.json
  public/icons/camera.svg
  public/icons/cup.svg
  public/icons/document.svg
  public/icons/home.svg
  public/icons/person.svg
  public/icons/search.svg
  public/images/default_profile.png
  src/app/admin/customer/detail/page.tsx
  src/app/admin/customer/page.tsx
  src/app/admin/layout.tsx
  src/app/admin/page.tsx
  src/app/admin/product/finished-teas/detail/page.tsx
  src/app/admin/product/finished-teas/page.tsx
  src/app/admin/product/loose-leaf-teas/detail/page.tsx
  src/app/admin/product/loose-leaf-teas/page.tsx
  src/app/layout.tsx
  src/app/survey/page.tsx
  src/components/common/FileInput/FileInput.module.scss
  src/components/common/FileInput/index.tsx
  src/components/ga/google-analytics.tsx
  src/components/page-layout/adminLayout/AdminLayout.module.scss
  src/components/page-layout/adminLayout/components/AdminCustomerPage/AdminCustomerPage.module.scss
  src/components/page-layout/adminLayout/components/AdminCustomerPage/EachCustomerPage/EachCustomerPage.module.scss
  src/components/page-layout/adminLayout/components/AdminCustomerPage/EachCustomerPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminCustomerPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminHomePage/AdminHomePage.module.scss
  src/components/page-layout/adminLayout/components/AdminHomePage/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/FinishedTeasPage/EachFinishedTeasPage/EachFinishedTeasPage.module.scss
  src/components/page-layout/adminLayout/components/AdminProductPage/FinishedTeasPage/EachFinishedTeasPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/FinishedTeasPage/FinishedTeasPage.module.scss
  src/components/page-layout/adminLayout/components/AdminProductPage/FinishedTeasPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/LooseLeafTeasPage/EachLooseLeafTeasPage/EachLooseLeafTeasPage.module.scss
  src/components/page-layout/adminLayout/components/AdminProductPage/LooseLeafTeasPage/EachLooseLeafTeasPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/LooseLeafTeasPage/LooseLeafTeasPage.module.scss
  src/components/page-layout/adminLayout/components/AdminProductPage/LooseLeafTeasPage/index.tsx
  src/components/page-layout/adminLayout/components/common/AdminHeader/AdminHeader.module.scss
  src/components/page-layout/adminLayout/components/common/AdminHeader/index.tsx
  src/components/page-layout/adminLayout/components/common/AdminSideBar/AdminSideBar.module.scss
  src/components/page-layout/adminLayout/components/common/AdminSideBar/index.tsx
  src/components/page-layout/adminLayout/components/common/BackButton/BackButton.module.scss
  src/components/page-layout/adminLayout/components/common/BackButton/index.tsx
  src/components/page-layout/adminLayout/components/common/DetailCard/DetailCard.module.scss
  src/components/page-layout/adminLayout/components/common/DetailCard/index.tsx
  src/components/page-layout/adminLayout/components/common/SearchBar/SearchBar.module.scss
  src/components/page-layout/adminLayout/components/common/SearchBar/index.tsx
  src/components/page-layout/adminLayout/components/common/SortBar/SortBar.module.scss
  src/components/page-layout/adminLayout/components/common/SortBar/index.tsx
  src/components/page-layout/adminLayout/components/common/SubmitButton/SubmitButton.module.scss
  src/components/page-layout/adminLayout/components/common/SubmitButton/index.tsx
  src/components/page-layout/adminLayout/components/common/Table/Table.module.scss
  src/components/page-layout/adminLayout/components/common/Table/index.tsx
  src/components/page-layout/adminLayout/index.tsx
  src/components/page-layout/adminLayout/types/productType.ts
  src/components/page-layout/adminLayout/types/userType.ts
  src/components/page-layout/myBlendingLayout/contexts/myBlendingContext.tsx
  src/lib/gtag.ts
Labels: feat

#43 [공통] 캐러셀 컴포넌트 구현
  public/icons/left_arrow.svg
  public/icons/right_arrow.svg
  public/images/carousel-test/IMG_5380.jpg
  public/images/carousel-test/IMG_5382.jpg
  public/images/carousel-test/IMG_5383.jpg
  public/images/carousel-test/IMG_5385.jpg
  public/images/carousel-test/IMG_5386.jpg
  public/images/carousel-test/IMG_5387.jpg
  public/images/carousel-test/IMG_5388.jpg
  public/images/carousel-test/IMG_5389.jpg
  public/images/carousel-test/IMG_5390.jpg
  public/images/carousel-test/IMG_5394.jpg
  public/images/carousel-test/IMG_5411.jpg
  src/app/layout.tsx
  src/app/page.tsx
  src/components/common/Carousel/Carousel.module.scss
  src/components/common/Carousel/Carousel.tsx
  src/components/common/Carousel/cardData.ts
  src/components/page-layout/mainLayout/MainLayout.module.scss
  src/components/page-layout/mainLayout/index.tsx
  src/fonts/02a5628b91717ae7191a2b202a5e93a4.woff
  src/styles/_mixins.scss
Labels: feat

#42 [공통] Footer구현
  public/icons/facebook.svg
  public/icons/github.svg
  public/icons/instagram.svg
  public/icons/twitter.svg
  public/icons/youtube.svg
  src/components/common/Footer/Company/Company.module.scss
  src/components/common/Footer/Company/Company.tsx
  src/components/common/Footer/Footer.module.scss
  src/components/common/Footer/Footer.tsx
  src/components/common/Footer/Participation/BackEnd/BackEnd.module.scss
  src/components/common/Footer/Participation/BackEnd/BackEnd.tsx
  src/components/common/Footer/Participation/Designer/Designer.module.scss
  src/components/common/Footer/Participation/Designer/Designer.tsx
  src/components/common/Footer/Participation/FrontEnd/FrontEnd.module.scss
  src/components/common/Footer/Participation/FrontEnd/FrontEnd.tsx
  src/components/common/Footer/Participation/Participation.module.scss
  src/components/common/Footer/Participation/Participation.tsx
  src/components/common/Footer/Sns/Sns.module.scss
  src/components/common/Footer/Sns/Sns.tsx
  src/styles/_color.scss
Labels: feat

#48 [페이지] 404페이지 구현
  public/icons/pageMovementArrow.svg
  public/icons/tea.svg
  src/app/layout.tsx
  src/app/not-found.module.scss
  src/app/not-found.tsx
  src/components/common/Footer/Participation/Designer/Designer.tsx
Labels: feat

#49 [페이지] 티 블렌딩 페이지 구현
  public/icons/kettle.svg
  public/icons/teabag.svg
  public/images/my-blending/bitter.svg
  public/images/my-blending/floral.svg
  public/images/my-blending/fruity.svg
  public/images/my-blending/sour.svg
  public/images/my-blending/spicy.svg
  public/images/my-blending/sweet.svg
  src/app/layout.tsx
  src/components/common/BlendingLabel/BlendingLabel.module.scss
  src/components/common/BlendingLabel/BlendingLabel.tsx
  src/components/common/BlendingLabel/constants/labelType.ts
  src/components/page-layout/myBlendingLayout/MyBlendingLayout.module.scss
  src/components/page-layout/myBlendingLayout/apis/looseLeafTeas.ts
  src/components/page-layout/myBlendingLayout/components/BlendingArea/BlendingArea.module.scss
  src/components/page-layout/myBlendingLayout/components/BlendingArea/ResultArea/ResultArea.module.scss
  src/components/page-layout/myBlendingLayout/components/BlendingArea/ResultArea/index.tsx
  src/components/page-layout/myBlendingLayout/components/BlendingArea/SelectedTeas/SelectedTeaCard/SelectedTeaCard.module.scss
  src/components/page-layout/myBlendingLayout/components/BlendingArea/SelectedTeas/SelectedTeaCard/index.tsx
  src/components/page-layout/myBlendingLayout/components/BlendingArea/SelectedTeas/SelectedTeas.module.scss
  src/components/page-layout/myBlendingLayout/components/BlendingArea/SelectedTeas/index.tsx
  src/components/page-layout/myBlendingLayout/components/BlendingArea/index.tsx
  src/components/page-layout/myBlendingLayout/components/FixedBottomBar/FixedBottomBar.module.scss
  src/components/page-layout/myBlendingLayout/components/FixedBottomBar/index.tsx
  src/components/page-layout/myBlendingLayout/components/SelectArea/SelectArea.module.scss
  src/components/page-layout/myBlendingLayout/components/SelectArea/SelectFlavor/FlavorSelect/FlavorSelect.module.scss
  src/components/page-layout/myBlendingLayout/components/SelectArea/SelectFlavor/FlavorSelect/index.tsx
  src/components/page-layout/myBlendingLayout/components/SelectArea/SelectFlavor/SelectFlavor.module.scss
  src/components/page-layout/myBlendingLayout/components/SelectArea/SelectFlavor/index.tsx
  src/components/page-layout/myBlendingLayout/components/SelectArea/TeaList/CheckIcon/CheckIcon.module.scss
  src/components/page-layout/myBlendingLayout/components/SelectArea/TeaList/CheckIcon/index.tsx
  src/components/page-layout/myBlendingLayout/components/SelectArea/TeaList/TeaList.module.scss
  src/components/page-layout/myBlendingLayout/components/SelectArea/TeaList/index.tsx
  src/components/page-layout/myBlendingLayout/components/SelectArea/index.tsx
  src/components/page-layout/myBlendingLayout/components/SortingMenu/SortingMenu.module.scss
  src/components/page-layout/myBlendingLayout/components/SortingMenu/TasteSortingList/TasteSortingList.module.scss
  src/components/page-layout/myBlendingLayout/components/SortingMenu/TasteSortingList/index.tsx
  src/components/page-layout/myBlendingLayout/components/SortingMenu/TypeSortingList/TypeSortingList.module.scss
  src/components/page-layout/myBlendingLayout/components/SortingMenu/TypeSortingList/index.tsx
  src/components/page-layout/myBlendingLayout/components/SortingMenu/index.tsx
  src/components/page-layout/myBlendingLayout/components/TeaCardList/TeaCard/AddRemoveIcon/AddRemoveIcon.module.scss
  src/components/page-layout/myBlendingLayout/components/TeaCardList/TeaCard/AddRemoveIcon/index.tsx
  src/components/page-layout/myBlendingLayout/components/TeaCardList/TeaCard/CheckIcon/CheckIcon.module.scss
  src/components/page-layout/myBlendingLayout/components/TeaCardList/TeaCard/CheckIcon/index.tsx
  src/components/page-layout/myBlendingLayout/components/TeaCardList/TeaCard/TeaCard.module.scss
  src/components/page-layout/myBlendingLayout/components/TeaCardList/TeaCard/index.tsx
  src/components/page-layout/myBlendingLayout/components/TeaCardList/TeaCardList.module.scss
  src/components/page-layout/myBlendingLayout/components/TeaCardList/index.tsx
  src/components/page-layout/myBlendingLayout/constants/flavors.ts
  src/components/page-layout/myBlendingLayout/constants/standards.ts
  src/components/page-layout/myBlendingLayout/contexts/myBlendingContext.tsx
  src/components/page-layout/myBlendingLayout/hooks/useGetLooseLeafTeas.ts
  src/components/page-layout/myBlendingLayout/index.tsx
  src/components/page-layout/myBlendingLayout/types/teaType.ts
  src/components/page-layout/surveyLayout/index.tsx
Labels: feat

#50 [페이지] admin 페이지 구현 및 api 미연결
  package-lock.json
  package.json
  public/icons/graph.svg
  public/icons/trashcan.svg
  public/images/default_product.png
  src/components/common/FileInput/CustomDropDownTrigger/index.tsx
  src/components/common/FileInput/FileInput.module.scss
  src/components/common/FileInput/index.tsx
  src/components/page-layout/adminLayout/components/AdminCustomerPage/EachCustomerPage/EachCustomerPage.module.scss
  src/components/page-layout/adminLayout/components/AdminCustomerPage/EachCustomerPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminCustomerPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminHomePage/AdminHomePage.module.scss
  src/components/page-layout/adminLayout/components/AdminHomePage/Graph/Graph.module.scss
  src/components/page-layout/adminLayout/components/AdminHomePage/Graph/index.tsx
  src/components/page-layout/adminLayout/components/AdminHomePage/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/FinishedTeasPage/EachFinishedTeasPage/EachFinishedTeasPage.module.scss
  src/components/page-layout/adminLayout/components/AdminProductPage/FinishedTeasPage/EachFinishedTeasPage/IngredientInput/DropDownInput/DropDownInput.module.scss
  src/components/page-layout/adminLayout/components/AdminProductPage/FinishedTeasPage/EachFinishedTeasPage/IngredientInput/DropDownInput/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/FinishedTeasPage/EachFinishedTeasPage/IngredientInput/IngredientInput.module.scss
  src/components/page-layout/adminLayout/components/AdminProductPage/FinishedTeasPage/EachFinishedTeasPage/IngredientInput/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/FinishedTeasPage/EachFinishedTeasPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/FinishedTeasPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/LooseLeafTeasPage/EachLooseLeafTeasPage/EachLooseLeafTeasPage.module.scss
  src/components/page-layout/adminLayout/components/AdminProductPage/LooseLeafTeasPage/EachLooseLeafTeasPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/LooseLeafTeasPage/index.tsx
  src/components/page-layout/adminLayout/components/common/AdminHeader/AdminHeader.module.scss
  src/components/page-layout/adminLayout/components/common/AdminHeader/AdminPageName/AdminPageName.module.scss
  src/components/page-layout/adminLayout/components/common/AdminHeader/AdminPageName/index.tsx
  src/components/page-layout/adminLayout/components/common/AdminHeader/index.tsx
  src/components/page-layout/adminLayout/hooks/useGAReport.ts
  src/components/page-layout/adminLayout/types/graphDataType.ts
  src/components/page-layout/adminLayout/types/productType.ts
  src/components/page-layout/adminLayout/types/userType.ts
  src/components/page-layout/adminLayout/utils/formatDataString.ts
  src/components/page-layout/surveyLayout/components/ButtonInputs/ButtonInput/index.tsx
  src/components/page-layout/surveyLayout/components/ButtonInputs/index.tsx
  src/components/page-layout/surveyLayout/components/CheckBoxInputs/CheckBoxInput/index.tsx
  src/components/page-layout/surveyLayout/components/CheckBoxInputs/index.tsx
  src/components/page-layout/surveyLayout/components/SurveyForm/index.tsx
  src/components/page-layout/surveyLayout/constants/teaTypes.ts
Labels: feat

#55 [페이지] 마이페이지(구독,주문) 구현
  src/apis/axiosInstance.ts
  src/app/(HeaderFooter)/layout.tsx
  src/app/(HeaderFooter)/my-blending/page.tsx
  src/app/(HeaderFooter)/my-page/order-subscribe/page.tsx
  src/app/(HeaderFooter)/page.tsx
  src/app/(HeaderFooter)/product/list/[id]/page.tsx
  src/app/(HeaderFooter)/product/list/page.tsx
  src/app/(HeaderFooter)/survey/page.tsx
  src/app/(NoHeaderFooter)/admin/customer/detail/page.tsx
  src/app/(NoHeaderFooter)/admin/customer/page.tsx
  src/app/(NoHeaderFooter)/admin/page.tsx
  src/app/(NoHeaderFooter)/admin/product/finished-teas/detail/page.tsx
  src/app/(NoHeaderFooter)/admin/product/finished-teas/page.tsx
  src/app/(NoHeaderFooter)/admin/product/loose-leaf-teas/detail/page.tsx
  src/app/(NoHeaderFooter)/admin/product/loose-leaf-teas/page.tsx
  src/app/(NoHeaderFooter)/sign-in/page.tsx
  src/app/(NoHeaderFooter)/sign-up/page.tsx
  src/app/admin/layout.tsx
  src/components/common/MyPageNav/MyPageNav.module.scss
  src/components/common/MyPageNav/MyPageNav.tsx
  src/components/common/MyPageSubNav/Box/Box.module.scss
  src/components/common/MyPageSubNav/Box/Box.tsx
  src/components/common/MyPageSubNav/Container/Container.module.scss
  src/components/common/MyPageSubNav/Container/Container.tsx
  src/components/common/MyPageSubNav/EnNav/EnNav.module.scss
  src/components/common/MyPageSubNav/EnNav/EnNav.tsx
  src/components/common/MyPageSubNav/KoNav/KoNav.module.scss
  src/components/common/MyPageSubNav/KoNav/KoNav.tsx
  src/components/common/MyPageSubNav/Root/Root.module.scss
  src/components/common/MyPageSubNav/Root/Root.tsx
  src/components/common/MyPageSubNav/index.ts
  src/components/common/MypageHeader/MypageHeader.module.scss
  src/components/common/MypageHeader/MypageHeader.tsx
  src/components/page-layout/mainLayout/index.tsx
  src/components/page-layout/orderSubscribeLayout/components/Card/Card.module.scss
  src/components/page-layout/orderSubscribeLayout/components/Card/Card.tsx
  src/components/page-layout/orderSubscribeLayout/components/orderSubscribeLayout.module.scss
  src/components/page-layout/orderSubscribeLayout/components/orderSubscribeLayout.tsx
  src/components/page-layout/signInLayout/signInForm/signInForm.module.scss
  src/components/page-layout/signInLayout/signInForm/signInForm.tsx
  src/components/page-layout/signInLayout/socialLogin/socialLogin.tsx
  src/components/page-layout/surveyLayout/index.tsx
  src/constants/route.ts
Labels: feat

#53 [페이지] 메인페이지
  public/icons/rightArrow.svg
  public/images/Ellipse 10.jpg
  public/images/main.png
  src/components/page-layout/mainLayout/MainLayout.module.scss
  src/components/page-layout/mainLayout/components/MainHeader/MainHeader.module.scss
  src/components/page-layout/mainLayout/components/MainHeader/MainHeader.tsx
  src/components/page-layout/mainLayout/index.tsx
  src/styles/_reset.scss
Labels: feat

#54 [페이지] 마이페이지 my-info 구현
  package-lock.json
  package.json
  public/icons/plus.svg
  src/app/(HeaderFooter)/my-page/my-info/page.tsx
  src/app/(NoHeaderFooter)/admin/layout.tsx
  src/components/common/BlendingLabel/BlendingLabel.module.scss
  src/components/common/BlendingLabel/constants/labelType.ts
  src/components/common/Button/Button.module.scss
  src/components/common/Button/index.tsx
  src/components/page-layout/myBlendingLayout/MyBlendingLayout.module.scss
  src/components/page-layout/myBlendingLayout/components/BlendingArea/ResultArea/ResultArea.module.scss
  src/components/page-layout/myBlendingLayout/components/BlendingArea/ResultArea/index.tsx
  src/components/page-layout/myBlendingLayout/index.tsx
  src/components/page-layout/myPageLayout/myInfo/MyInfoLayout.module.scss
  src/components/page-layout/myPageLayout/myInfo/apis/profileApis.ts
  src/components/page-layout/myPageLayout/myInfo/components/AddressChange/AddressChange.module.scss
  src/components/page-layout/myPageLayout/myInfo/components/AddressChange/index.tsx
  src/components/page-layout/myPageLayout/myInfo/components/PasswordChange/PasswordChange.module.scss
  src/components/page-layout/myPageLayout/myInfo/components/PasswordChange/index.tsx
  src/components/page-layout/myPageLayout/myInfo/components/ProfileChange/MyInfoFileInput/MyInfoFileInput.module.scss
  src/components/page-layout/myPageLayout/myInfo/components/ProfileChange/MyInfoFileInput/index.tsx
  src/components/page-layout/myPageLayout/myInfo/components/ProfileChange/ProfileChange.module.scss
  src/components/page-layout/myPageLayout/myInfo/components/ProfileChange/index.tsx
  src/components/page-layout/myPageLayout/myInfo/components/common/MyPageInput/MyPageInput.module.scss
  src/components/page-layout/myPageLayout/myInfo/components/common/MyPageInput/index.tsx
  src/components/page-layout/myPageLayout/myInfo/components/common/MyPageTitle/MyPageTitle.module.scss
  src/components/page-layout/myPageLayout/myInfo/components/common/MyPageTitle/index.tsx
  src/components/page-layout/myPageLayout/myInfo/contexts/myInfoContext.tsx
  src/components/page-layout/myPageLayout/myInfo/hooks/useGetMyInfo.ts
  src/components/page-layout/myPageLayout/myInfo/hooks/usePatchUserData.ts
  src/components/page-layout/myPageLayout/myInfo/index.tsx
  src/components/page-layout/surveyLayout/index.tsx
  src/lib/supabase.ts
  src/utils/supabaseUtils.ts
Labels: feat

#60 [페이지] 완제품 관리자 페이지 기능 구현
  next.config.mjs
  src/app/(NoHeaderFooter)/admin/product/finished-teas/page.tsx
  src/app/(NoHeaderFooter)/admin/product/finished-teas/post/page.tsx
  src/app/(NoHeaderFooter)/admin/product/loose-leaf-teas/page.tsx
  src/app/(NoHeaderFooter)/admin/product/loose-leaf-teas/post/page.tsx
  src/components/page-layout/adminLayout/apis/customersApis.ts
  src/components/page-layout/adminLayout/apis/finishedTeasApis.ts
  src/components/page-layout/adminLayout/components/AdminCustomerPage/EachCustomerPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/FinishedTeasPage/EachFinishedTeasPage/IngredientInput/DropDownInput/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/FinishedTeasPage/EachFinishedTeasPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/FinishedTeasPage/PostFinishedTeasPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/FinishedTeasPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/LooseLeafTeasPage/EachLooseLeafTeasPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/LooseLeafTeasPage/PostLooseLeafTeasPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/LooseLeafTeasPage/index.tsx
  src/components/page-layout/adminLayout/components/common/BackButton/BackButton.module.scss
  src/components/page-layout/adminLayout/components/common/FileInput/CustomDropDownTrigger/index.tsx
  src/components/page-layout/adminLayout/components/common/FileInput/FileInput.module.scss
  src/components/page-layout/adminLayout/components/common/FileInput/index.tsx
  src/components/page-layout/adminLayout/components/common/FinIshedTeaForm/FinishedTeaForm.module.scss
  src/components/page-layout/adminLayout/components/common/FinIshedTeaForm/IngredientInput/DropDownInput/DropDownInput.module.scss
  src/components/page-layout/adminLayout/components/common/FinIshedTeaForm/IngredientInput/DropDownInput/index.tsx
  src/components/page-layout/adminLayout/components/common/FinIshedTeaForm/IngredientInput/IngredientInput.module.scss
  src/components/page-layout/adminLayout/components/common/FinIshedTeaForm/IngredientInput/index.tsx
  src/components/page-layout/adminLayout/components/common/FinIshedTeaForm/index.tsx
  src/components/page-layout/adminLayout/components/common/LooseLeafTeaForm/LooseLeafTeaForm.module.scss
  src/components/page-layout/adminLayout/components/common/LooseLeafTeaForm/index.tsx
  src/components/page-layout/adminLayout/components/common/PageButtons/PageButtons.module.scss
  src/components/page-layout/adminLayout/components/common/PageButtons/index.tsx
  src/components/page-layout/adminLayout/components/common/SortBar/SortBar.module.scss
  src/components/page-layout/adminLayout/components/common/SortBar/index.tsx
  src/components/page-layout/adminLayout/components/common/Table/Table.module.scss
  src/components/page-layout/adminLayout/components/common/Table/index.tsx
  src/components/page-layout/adminLayout/constants/categories.ts
  src/components/page-layout/adminLayout/hooks/useManageCustomers.ts
  src/components/page-layout/adminLayout/hooks/useManageIngredients.ts
  src/components/page-layout/adminLayout/hooks/useManageTeas.ts
  src/components/page-layout/adminLayout/types/productType.ts
  src/components/page-layout/myBlendingLayout/contexts/myBlendingContext.tsx
  src/components/page-layout/myPageLayout/myInfo/components/AddressChange/index.tsx
  src/components/page-layout/myPageLayout/myInfo/components/ProfileChange/MyInfoFileInput/index.tsx
  src/components/page-layout/myPageLayout/myInfo/components/ProfileChange/index.tsx
  src/components/page-layout/surveyLayout/components/ButtonInputs/index.tsx
  src/components/page-layout/surveyLayout/constants/teaTypes.ts
Labels: feat

#62 [공통] GNB 컴포넌트
  src/apis/getUserInfo.ts
  src/components/common/GlobalNavBar/AuthButton/AuthButton.module.scss
  src/components/common/GlobalNavBar/AuthButton/AuthButton.tsx
  src/components/common/GlobalNavBar/AuthButton/Profile.module.scss
  src/components/common/GlobalNavBar/AuthButton/Profile.tsx
  src/components/common/GlobalNavBar/GlobalNavBar.module.scss
  src/components/common/GlobalNavBar/GlobalNavBar.tsx
  src/components/common/GlobalNavBar/MyInfo/MyInfo.module.scss
  src/components/common/GlobalNavBar/MyInfo/MyInfo.tsx
  src/components/common/GlobalNavBar/MyInfo/MyInfoContent.tsx
  src/components/common/GlobalNavBar/MyInfo/PopupHeader.tsx
  src/components/common/GlobalNavBar/component/AuthButton/AuthButton.module.scss
  src/components/common/GlobalNavBar/component/AuthButton/AuthButton.tsx
  src/components/common/GlobalNavBar/component/AuthButton/Profile.tsx
  src/components/common/GlobalNavBar/component/Hamburger/Hamburger.module.scss
  src/components/common/GlobalNavBar/component/Hamburger/Hamburger.tsx
  src/components/common/GlobalNavBar/component/MyInfo/MyInfo.tsx
  src/components/common/GlobalNavBar/component/MyInfo/MyInfoContent.tsx
  src/components/page-layout/mainLayout/components/MainHeader/MainHeader.module.scss
  src/components/page-layout/mainLayout/components/MainHeader/MainHeader.tsx
  src/constants/route.ts
  src/hooks/query/useUserInfoQuery.ts
  src/hooks/useOutsideClick.ts
Labels: refactor

#63 [refactor] 코드리팩토링
  README.md
  next.config.mjs
  public/icons/star.svg
  src/apis/axiosInstance.ts
  src/app/(HeaderFooter)/layout.tsx
  src/app/(HeaderFooter)/reviews/page.tsx
  src/components/common/Card/Card.tsx
  src/components/common/GlobalNavBar/constants/menuItem.ts
  src/components/common/Layout/Layout.module.scss
  src/components/common/Layout/Layout.tsx
  src/components/common/MyPageNav/MyPageNav.tsx
  src/components/common/MypageHeader/MypageHeader.tsx
  src/components/common/Pagenation/apis/getPagenationItems.ts
  src/components/common/Skeleton/Skeleton.tsx
  src/components/common/SubHeader/SubHeader.module.scss
  src/components/common/SubHeader/SubHeader.tsx
  src/components/page-layout/mainLayout/index.tsx
  src/components/page-layout/myPageLayout/myInfo/index.tsx
  src/components/page-layout/orderSubscribeLayout/components/Card/Card.module.scss
  src/components/page-layout/orderSubscribeLayout/components/Card/Card.tsx
  src/components/page-layout/orderSubscribeLayout/components/orderSubscribeLayout.tsx
  src/components/page-layout/productListLayout/ProductList/ProductList.tsx
  src/components/page-layout/productListLayout/ProductNav/CategoryNav/CategoryNav.tsx
  src/components/page-layout/productListLayout/constants/index.ts
  src/components/page-layout/productListLayout/productListLayout.module.scss
  src/components/page-layout/productListLayout/productListLayout.tsx
  src/components/page-layout/productListLayout/types/index.ts
  src/components/page-layout/reviewLayout/apis/index.ts
  src/components/page-layout/reviewLayout/components/Card/Card.module.scss
  src/components/page-layout/reviewLayout/components/Card/Card.tsx
  src/components/page-layout/reviewLayout/components/ReviewLayout.module.scss
  src/components/page-layout/reviewLayout/components/ReviewLayout.tsx
  src/components/page-layout/reviewLayout/types/index.ts
  src/components/page-layout/signInLayout/signInForm/signInForm.tsx
  src/components/page-layout/signInLayout/signInLayout.module.scss
  src/components/page-layout/signUpLayout/signUpLayout.module.scss
Labels: feat, refactor

#64 [페이지] admin페이지 기능구현
  src/components/page-layout/adminLayout/apis/customersApis.ts
  src/components/page-layout/adminLayout/apis/looseLeafTeasApis.ts
  src/components/page-layout/adminLayout/components/AdminCustomerPage/AdminCustomerPage.module.scss
  src/components/page-layout/adminLayout/components/AdminCustomerPage/EachCustomerPage/EachCustomerPage.module.scss
  src/components/page-layout/adminLayout/components/AdminCustomerPage/EachCustomerPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminCustomerPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/FinishedTeasPage/EachFinishedTeasPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/FinishedTeasPage/PostFinishedTeasPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/FinishedTeasPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/LooseLeafTeasPage/EachLooseLeafTeasPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/LooseLeafTeasPage/PostLooseLeafTeasPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/LooseLeafTeasPage/index.tsx
  src/components/page-layout/adminLayout/components/common/FinIshedTeaForm/FinishedTeaForm.module.scss
  src/components/page-layout/adminLayout/components/common/FinIshedTeaForm/index.tsx
  src/components/page-layout/adminLayout/components/common/LooseLeafTeaForm/LooseLeafTeaForm.module.scss
  src/components/page-layout/adminLayout/components/common/LooseLeafTeaForm/index.tsx
  src/components/page-layout/adminLayout/components/common/PageButtons/index.tsx
  src/components/page-layout/adminLayout/components/common/Table/index.tsx
  src/components/page-layout/adminLayout/hooks/useManageCustomers.ts
  src/components/page-layout/adminLayout/hooks/useManageIngredients.ts
  src/components/page-layout/adminLayout/types/productType.ts
  src/components/page-layout/adminLayout/utils/processIngredientData.ts
  src/components/page-layout/myBlendingLayout/constants/flavors.ts
  src/components/page-layout/myPageLayout/myInfo/apis/profileApis.ts
  src/components/page-layout/myPageLayout/myInfo/components/ProfileChange/index.tsx
  src/components/page-layout/myPageLayout/myInfo/contexts/myInfoContext.tsx
  src/components/page-layout/myPageLayout/myInfo/hooks/usePatchUserData.ts
  src/utils/supabaseUtils.ts
Labels: feat, hotfix

#66 [페이지] 마이페이지 리뷰 UI 외 버그 수정
  public/icons/emptyStar.svg
  public/icons/fullStar.svg
  public/icons/halfStar.svg
  public/icons/pencil.svg
  src/app/(HeaderFooter)/my-page/my-review/layout.tsx
  src/app/(HeaderFooter)/my-page/my-review/page.tsx
  src/app/(HeaderFooter)/my-page/my-review/text-review/page.tsx
  src/components/common/modal/BackdropModal/BackdropModal.module.scss
  src/components/page-layout/adminLayout/components/AdminCustomerPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/FinishedTeasPage/EachFinishedTeasPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/FinishedTeasPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/LooseLeafTeasPage/index.tsx
  src/components/page-layout/adminLayout/components/common/FileInput/index.tsx
  src/components/page-layout/adminLayout/components/common/FinIshedTeaForm/IngredientInput/DropDownInput/index.tsx
  src/components/page-layout/adminLayout/components/common/FinIshedTeaForm/IngredientInput/index.tsx
  src/components/page-layout/adminLayout/components/common/Table/index.tsx
  src/components/page-layout/adminLayout/utils/processIngredientData.ts
  src/components/page-layout/myBlendingLayout/contexts/myBlendingContext.tsx
  src/components/page-layout/myPageLayout/myInfo/components/ProfileChange/MyInfoFileInput/index.tsx
  src/components/page-layout/myPageLayout/myReview/MyReviewLayout.module.scss
  src/components/page-layout/myPageLayout/myReview/components/MyReviewPage/MyReviewPage.module.scss
  src/components/page-layout/myPageLayout/myReview/components/MyReviewPage/index.tsx
  src/components/page-layout/myPageLayout/myReview/components/MyTextReviewPage/MyTextReviewPage.module.scss
  src/components/page-layout/myPageLayout/myReview/components/MyTextReviewPage/index.tsx
  src/components/page-layout/myPageLayout/myReview/components/common/MyReviewCard/MyReivewCard.module.scss
  src/components/page-layout/myPageLayout/myReview/components/common/MyReviewCard/index.tsx
  src/components/page-layout/myPageLayout/myReview/components/common/MyReviewNavBar/MyReviewNavBar.module.scss
  src/components/page-layout/myPageLayout/myReview/components/common/MyReviewNavBar/index.tsx
  src/components/page-layout/myPageLayout/myReview/components/common/RateStars/RateStars.module.scss
  src/components/page-layout/myPageLayout/myReview/components/common/RateStars/index.tsx
  src/components/page-layout/myPageLayout/myReview/components/common/ReviewModal/ReviewModal.module.scss
  src/components/page-layout/myPageLayout/myReview/components/common/ReviewModal/index.tsx
  src/components/page-layout/myPageLayout/myReview/components/common/StarImage/index.tsx
  src/components/page-layout/myPageLayout/myReview/index.tsx
  src/components/page-layout/myPageLayout/myReview/types/likesType.ts
  src/components/page-layout/surveyLayout/apis/postSurvey.ts
  src/components/page-layout/surveyLayout/components/ButtonInputs/ButtonInput/ButtonInput.module.scss
  src/components/page-layout/surveyLayout/components/ButtonInputs/ButtonInput/index.tsx
  src/components/page-layout/surveyLayout/components/ButtonInputs/index.tsx
  src/components/page-layout/surveyLayout/components/CheckBoxInputs/CheckBoxInput/CheckBoxInput.module.scss
  src/components/page-layout/surveyLayout/components/CheckBoxInputs/CheckBoxInput/index.tsx
  src/components/page-layout/surveyLayout/components/FormDesign/FormDesign.module.scss
  src/components/page-layout/surveyLayout/components/FormIcon/FormIcon.module.scss
  src/components/page-layout/surveyLayout/components/SurveyForm/index.tsx
  src/components/page-layout/surveyLayout/hooks/usePostSurvey.ts
  src/lib/gtag.ts
Labels: bug, feat, hotfix

#67 [페이지] 장바구니 페이지
  next.config.mjs
  public/icons/close.svg
  public/icons/location.svg
  public/icons/minus.svg
  public/icons/plus.svg
  public/icons/plusIcon.svg
  src/apis/getUserInfo.ts
  src/app/(HeaderFooter)/cart/page.tsx
  src/components/common/Accordion/Accordion.tsx
  src/components/common/Accordion/AccordionContent.tsx
  src/components/common/Accordion/AccordionTrigger.tsx
  src/components/common/Accordion/contexts/AccordionContext.ts
  src/components/common/Card/Card.tsx
  src/components/common/GlobalNavBar/AuthButton/AuthButton.tsx
  src/components/common/GlobalNavBar/AuthButton/Profile.tsx
  src/components/common/GlobalNavBar/GlobalNavBar.tsx
  src/components/common/GlobalNavBar/MyInfo/MyInfo.module.scss
  src/components/common/GlobalNavBar/MyInfo/MyInfoContent.tsx
  src/components/common/GlobalNavBar/MyInfo/PopupHeader.tsx
  src/components/common/QuantityButton/QuantityButton.module.scss
  src/components/common/QuantityButton/QuantityButton.tsx
  src/components/common/modal/BackdropModal/BackdropModal.module.scss
  src/components/common/modal/BackdropModal/BackdropModal.tsx
  src/components/page-layout/cartLayout/CartLayout.module.scss
  src/components/page-layout/cartLayout/CartLayout.tsx
  src/components/page-layout/cartLayout/apis/cartApi.ts
  src/components/page-layout/cartLayout/components/CartItem/CartItem.module.scss
  src/components/page-layout/cartLayout/components/CartItem/CartItem.tsx
  src/components/page-layout/cartLayout/components/CartView/CartView.module.scss
  src/components/page-layout/cartLayout/components/CartView/CartView.tsx
  src/components/page-layout/cartLayout/components/CheckoutSummary/CheckoutSummary.module.scss
  src/components/page-layout/cartLayout/components/CheckoutSummary/CheckoutSummary.tsx
  src/components/page-layout/cartLayout/components/DeleteConfirmModal/DeleteConfirmModal.module.scss
  src/components/page-layout/cartLayout/components/DeleteConfirmModal/DeleteConfirmModal.tsx
  src/components/page-layout/cartLayout/components/DeliveryAddress/DeliveryAddress.module.scss
  src/components/page-layout/cartLayout/components/DeliveryAddress/DeliveryAddress.tsx
  src/components/page-layout/cartLayout/components/PriceDetails/PriceDetails.module.scss
  src/components/page-layout/cartLayout/components/PriceDetails/PriceDetails.tsx
  src/components/page-layout/cartLayout/components/SelectAllCheckbox/SelectAllCheckbox.module.scss
  src/components/page-layout/cartLayout/components/SelectAllCheckbox/SelectAllCheckbox.tsx
  src/components/page-layout/cartLayout/hooks/useAddCartItemMutation.ts
  src/components/page-layout/cartLayout/hooks/useCartItemQuery.ts
  src/components/page-layout/cartLayout/hooks/useDeleteItemMutation.ts
  src/components/page-layout/cartLayout/hooks/usePatchCartItemMutation.ts
  src/components/page-layout/cartLayout/hooks/useSelcetedDeleteCartItemMutation.ts
  src/components/page-layout/cartLayout/types/cartApiType.ts
  src/components/page-layout/productListLayout/ProductList/ProductList.tsx
  src/constants/route.ts
  src/hooks/query/useUserInfoQuery.ts
  src/types/users/type.ts
Labels: feat

#71 [refactor] access토큰api수정
  public/icons/footer_logo.svg
  public/images/used.svg
  src/apis/axiosInstance.ts
  src/app/(HeaderFooter)/layout.tsx
  src/app/(HeaderFooter)/my-page/my-coupon/page.tsx
  src/components/common/Card/Card.tsx
  src/components/common/Carousel/Carousel.tsx
  src/components/common/Footer/Footer.module.scss
  src/components/common/Footer/Footer.tsx
  src/components/common/Header/Header.tsx
  src/components/common/Pagenation/apis/getPagenationItems.ts
  src/components/page-layout/mainLayout/apis/getMainItems.ts
  src/components/page-layout/mainLayout/index.tsx
  src/components/page-layout/myCouponLayout/components/Coupon/Coupon.module.scss
  src/components/page-layout/myCouponLayout/components/Coupon/Coupon.tsx
  src/components/page-layout/myCouponLayout/myCouponLayout.module.scss
  src/components/page-layout/myCouponLayout/myCouponLayout.tsx
  src/components/page-layout/productListLayout/ProductList/ProductList.tsx
  src/components/page-layout/productListLayout/types/index.ts
  src/components/page-layout/signUpLayout/signUpForm/signUpForm.tsx
  src/components/page-layout/surveyLayout/components/FormIcon/FormIcon.module.scss
  src/utils/supabaseUtils.ts
Labels: refactor

#75 [refactor] 리팩토링
  src/apis/axiosInstance.ts
  src/apis/getUserInfo.ts
  src/components/common/Pagenation/apis/getPagenationItems.ts
  src/components/page-layout/adminLayout/apis/customersApis.ts
  src/components/page-layout/adminLayout/apis/finishedTeasApis.ts
  src/components/page-layout/adminLayout/apis/looseLeafTeasApis.ts
  src/components/page-layout/cartLayout/apis/cartApi.ts
  src/components/page-layout/mainLayout/apis/getMainItems.ts
  src/components/page-layout/myBlendingLayout/apis/looseLeafTeas.ts
  src/components/page-layout/myCouponLayout/apis/index.ts
  src/components/page-layout/myCouponLayout/components/Coupon/Coupon.tsx
  src/components/page-layout/myCouponLayout/myCouponLayout.module.scss
  src/components/page-layout/myCouponLayout/myCouponLayout.tsx
  src/components/page-layout/myPageLayout/myInfo/apis/profileApis.ts
  src/components/page-layout/myPageLayout/myReview/apis/reviewApis.ts
  src/components/page-layout/myPageLayout/saveList/apis/blendingTeasSaveApis.ts
  src/components/page-layout/myPageLayout/saveList/apis/finishedTeasSaveApis.ts
  src/components/page-layout/reviewLayout/apis/index.ts
  src/components/page-layout/signInLayout/apis/postSignInFormData.ts
  src/components/page-layout/signUpLayout/apis/postSignUpForm.ts
  src/components/page-layout/surveyLayout/apis/postSurvey.ts
Labels: refactor

#77 [공통] 쿠폰 컴포넌트 수정
  src/components/page-layout/myCouponLayout/components/Coupon/Coupon.tsx
Labels: refactor

#78 [hotfix] axios 인터셉터 주석처리
  src/apis/axiosInstance.ts
Labels: refactor

#80 [fix] 경로 수정 및 인스턴스 수정
  src/components/page-layout/orderLayout/hooks/usePaymentMutation.ts
Labels: bug

#82 [페이지] 프리패칭 기능 추가
  src/components/page-layout/myCouponLayout/myCouponLayout.tsx
  src/components/page-layout/productListLayout/ProductList/ProductList.tsx
Labels: feat

#83 [fix] survey 페이지 쿼리 수정
  src/components/page-layout/surveyLayout/components/SurveyForm/index.tsx
Labels: bug

#84 [fix] build 오류 수정
  src/components/page-layout/orderLayout/components/OrderProduct/OrderProduct.tsx
  src/components/page-layout/orderLayout/components/PaymentSummary/PaymentSummary.tsx
Labels: hotfix

#85 [페이지] 마이리뷰 페이지, 찜 페이지 mock 데이터 구현
  public/icons/close.svg
  src/components/common/Loader/Loader.module.scss
  src/components/common/Loader/index.tsx
  src/components/page-layout/adminLayout/components/AdminCustomerPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminHomePage/Graph/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/FinishedTeasPage/index.tsx
  src/components/page-layout/adminLayout/components/AdminProductPage/LooseLeafTeasPage/index.tsx
  src/components/page-layout/myBlendingLayout/components/SelectArea/TeaList/TeaList.module.scss
  src/components/page-layout/myBlendingLayout/components/SelectArea/TeaList/index.tsx
  src/components/page-layout/myBlendingLayout/contexts/myBlendingContext.tsx
  src/components/page-layout/myPageLayout/myReview/components/MyReviewPage/index.tsx
  src/components/page-layout/myPageLayout/myReview/components/MyTextReviewPage/index.tsx
  src/components/page-layout/myPageLayout/myReview/components/common/ReviewModal/index.tsx
  src/components/page-layout/myPageLayout/saveList/apis/blendingTeasSaveApis.ts
  src/components/page-layout/myPageLayout/saveList/apis/finishedTeasSaveApis.ts
  src/components/page-layout/myPageLayout/saveList/components/blendingSavePage/index.tsx
  src/components/page-layout/myPageLayout/saveList/components/common/SavePageCard/SavePageCard.module.scss
  src/components/page-layout/myPageLayout/saveList/components/common/SavePageCard/index.tsx
  src/components/page-layout/myPageLayout/saveList/components/saveListPage/SaveListPage.module.scss
  src/components/page-layout/myPageLayout/saveList/components/saveListPage/index.tsx
  src/components/page-layout/myPageLayout/saveList/hooks/useHandleBlendingTeasSave.ts
  src/components/page-layout/myPageLayout/saveList/hooks/useHandleFinishedTeasSave.ts
Labels: feat, hotfix

#86 [페이지] 제품 상세페이지
  public/icons/heart.svg
  public/images/my-blending/myBlending.png
  src/app/(HeaderFooter)/my-blending/result/page.tsx
  src/app/(HeaderFooter)/product/list/[id]/page.tsx
  src/components/common/Card/Card.tsx
  src/components/page-layout/cartLayout/components/CartView/CartView.tsx
  src/components/page-layout/cartLayout/hooks/useSelcetedDeleteCartItemMutation.ts
  src/components/page-layout/myBlendingResultLayout/MyBlendingResultLayout.module.scss
  src/components/page-layout/myBlendingResultLayout/MyBlendingResultLayout.tsx
  src/components/page-layout/myBlendingResultLayout/components/ResultDetail/ResultDetail.module.scss
  src/components/page-layout/myBlendingResultLayout/components/ResultDetail/ResultDetail.tsx
  src/components/page-layout/myBlendingResultLayout/components/ResultMetrics/ResultMetrics.module.scss
  src/components/page-layout/myBlendingResultLayout/components/ResultMetrics/ResultMetrics.tsx
  src/components/page-layout/orderLayout/components/OrderProduct/OrderProduct.tsx
  src/components/page-layout/orderLayout/components/PaymentSummary/PaymentSummary.tsx
  src/components/page-layout/orderLayout/hooks/usePaymentMutation.ts
  src/components/page-layout/productLayout/ProductLayout.module.scss
  src/components/page-layout/productLayout/ProductLayout.tsx
  src/components/page-layout/productLayout/apis/ingredientApi.ts
  src/components/page-layout/productLayout/apis/productApi.ts
  src/components/page-layout/productLayout/components/ProductDetail/ProductDetail.module.scss
  src/components/page-layout/productLayout/components/ProductDetail/ProductDetail.tsx
  src/components/page-layout/productLayout/components/ProductMetrics/ProductMetrics.module.scss
  src/components/page-layout/productLayout/components/ProductMetrics/ProductMetrics.tsx
  src/components/page-layout/productLayout/hooks/useGetIngredientQueries.ts
  src/components/page-layout/productLayout/hooks/useGetTeaDetailQuery.ts
Labels: feat

#81 [페이지] 제품 추천 페이지 (설문 결과)
  package-lock.json
  package.json
  public/images/checklist.png
  public/images/surveyResultBanner.png
  src/apis/getUserInfo.ts
  src/app/(HeaderFooter)/recommend/page.tsx
  src/components/common/Carousel/Carousel.module.scss
  src/components/page-layout/recommendLayout/RecommendLayout.module.scss
  src/components/page-layout/recommendLayout/apis/getSurveyResults.ts
  src/components/page-layout/recommendLayout/apis/useGetSurveyResults.ts
  src/components/page-layout/recommendLayout/components/RecommendList.module.scss
  src/components/page-layout/recommendLayout/components/RecommendList.tsx
  src/components/page-layout/recommendLayout/components/RecommendListData.ts
  src/components/page-layout/recommendLayout/components/SurveyResults.module.scss
  src/components/page-layout/recommendLayout/components/SurveyResults.tsx
  src/components/page-layout/recommendLayout/index.tsx
Labels: feat
